spring.application.name=investingApp-backend
spring.output.ansi.enabled=always

# Model (la API key viene del sistema: OPENAI_API_KEY)
openai.model=gpt-4o-mini
#spring.profiles.active=h2
spring.profiles.active=dev-pg

# --- twelve data credentials --- #
twelvedata.base-url=https://api.twelvedata.com
twelvedata.api-key=${TWELVEDATA_API_KEY}