# --- H2 properties ---
# https://www.youtube.com/watch?v=8QBJMxyXIqc
spring.sql.init.platform=h2

########################
# Disk-based database: #
########################
# Los datos de la base de datos H2 se almacenan en un archivo fisico
# que genera el sistema con la extension .mv.db. en la ruta indicada.
spring.datasource.url=jdbc:h2:file:./data/investing_db;AUTO_SERVER=true

#######################
# In-memory database: #
#######################
# Los datos se cargan en la memoria cuando se inicia la base de datos
# y se mantienen en ella durante la duracion de la ejecucion.
# No se realiza ninguna escritura o lectura directamente en el disco.
#spring.datasource.url=jdbc:h2:mem:investing_db;DB_CLOSE_DELAY=-1

spring.h2.console.path=/h2-console
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.datasource.driver-class-name=org.h2.Driver

##################
# JPA properties #
##################
# Mostrar queries en consola
spring.jpa.show-sql=false
# actualizar base de datos y crear entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# hibernate genera SQL optimizado