#https://cloud.yugabyte.com/ bbdd en yugabyte, acceso con gmail
#video yugabyte: https://youtu.be/zd57J1TzqLo?si=lFDYSH3rj3Uowp5t
# --- PostgreSQL properties ---
spring.datasource.url=jdbc:postgresql://localhost:5432/investing_local_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
#spring.datasource.url=${YUGABYTE_URL}
spring.datasource.username=postgres
spring.datasource.password=root
#spring.datasource.username=${YUGABYTE_USER}
#spring.datasource.password=${YUGABYTE_PASS}

# JPA properties
# Mostrar queries en consola
#spring.jpa.show-sql=true
# actualizar base de datos y crear entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# hibernate genera SQL optimizado
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect

# --- MAIL properties ---
mail.urlFront=http://localhost:4200/reset-password/